nepochs: 10
seed: 42

data:
  trainpath: "./data/segmentation_dataset_cropped"
  batch_size: 16       
  num_workers: 4    
  valid_ratio: 0.2
  resize: 224
  active_learning: True
  al_path: "active_learning/pool_labelled"
  val_path: "active_learning/validation_data_stratified"


model:
  class: "DeepLabV3Plus"
  backbone: "resnet34"
  pretrained: true

optim:
  algo: "AdamW"         
  params:
    lr: 0.0009
    weight_decay: 0.01 

loss: "TverskyLoss"

logging:
  logdir: "./logs"      
