nepochs: 50
seed: 42

data:
  trainpath: "./data/segmentation_dataset_cropped"
  batch_size: 8        
  num_workers: 4    
  valid_ratio: 0.2
  resize: 224

model:
  class: "DeepLabV3Plus"
  backbone: "resnet34"
  pretrained: true

optim:
  algo: "AdamW"         
  params:
    lr: 0.0001
    weight_decay: 0.01 

loss: "TverskyLoss"

logging:
  logdir: "./logs"      
