nepochs: 30
seed: 42

data:
  trainpath: "./data/segmentation_dataset_cropped"
  batch_size: 8    
  num_workers: 4    
  valid_ratio: 0.2
  resize: 448
  active_learning: True
  al_path: "active_learning/pool_labelled_full"
  val_path: "active_learning/validation_data_stratified"
  augmentations: "tl_occlusion_affine_domain_fda"


model:
  class: "Unet"
  backbone: "resnet34"
  pretrained: true

optim:
  algo: "AdamW"         
  params:
    lr: 0.01
    weight_decay: 0.01 

loss: "TverskyLoss"

logging:
  logdir: "./logs"      
